### ISSUE TITLE
{ found: true } possible unexpected behavior.

### ISSUE THREAD

**Issue by Nicktho** [Prismatik/redbeard#1]
There are currently no tests to check whether `found: true` is included in the resolved object from a call to `get` in the controllers.

Adding such a test found it breaks when `params.count !== true`, even if responses are found, I assume its this line here: https://github.com/Prismatik/redbeard/blob/master/controller/controller.mustache#L93

The tag probably should be `result`

**Comment by nwinch** [comment]
> Adding such a test found it breaks
@Nicktho Just checking - did you add a test for this at some point?

**Comment by davidbanham** [comment]
`found` should never actually be serialised over the API. It's just an internal flag used to denote "Hey! Send a 404!". It's being removed, so closing this issue.
