### ISSUE TITLE
.update function validations not working correctly

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/redbeard#101]
This is related to https://github.com/Prismatik/redbeard/issues/100
When performing validations on the model for an update, we need to first merge the changes into the current version of the object before attempting to validate. When performing an update you do not need to provide all fields, just the ones that are changing and tests are sending all fields across.

https://github.com/Prismatik/hosportal/commit/29c9b399cfeeb3c20936d6b64aad7adef76cb94b

**Comment by MadRabbit** [comment]
this is resolved in the `thinky` branch. thinky has a JSON schema based validator in it and it does all the checks before create and update automatically based on it
