### ISSUE TITLE
Model .get should support an array of values (as an OR condition)

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/redbeard#114]
To do this in hosportal I have basically re-written the buildQuery function...

https://github.com/Prismatik/hosportal/commit/bb6dc434518f4daeb972ae1d30d00c50275891e4

**Comment by s-taylor** [comment]
And we should add a test to each model...

https://github.com/Prismatik/hosportal/commit/ff333452994e6502effc5e27874ed7da6099c49b

**Comment by MadRabbit** [comment]
it seems like an application specific case, it think it would more sense to leave this out to a specific implementation

**Comment by MadRabbit** [comment]
i'm closing this as there is no further discussion on this matter. the outcome is that this logic should be implemented per application in specific controllers
