### ISSUE TITLE
Schema validation for migrations

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#119]
Messing around with migrations for the first time today, and it reminded me of how easily inconsistent data can be injected with migrations - even with tests.

So I [added schema validation to the migration methods](https://github.com/Prismatik/hosportal/pull/58), which seems to work well.  It errors out if the data you want to inject with the migration doesn't pass validation.  Better to know this asap, than having to purge bad data later on!

Thoughts on adding this?

**Comment by davidbanham** [comment]
This ended up being resolved in the negative on that other repo. The crux was:

> This will probably bite you in the future. The data you've got in this migration is a valid record now, but say in a month's time we add the .specialities array which is a required field.
> 
> When we do that, we dutifully add a migration to add a blank specialities prop to all hospitals.
> 
> However! Next time we run the codebase against a blank database, the migration you wrote today will fail when it attempts to validate these older versions of the document against the newest version of the schema. Disaster, sadness and red CI badges abound.

**Comment by nwinch** [comment]
For posterity's sake I'll mentioned what happened to migration validation on Hosportal:

We ended up reinstating validations for seed migrations only.  The thinking is, that seed data will _only_ be used for local/test environments - where seed data is the only data necessary - and should always be up to date and can happily allow the data to be changed/altered at any point, so validating seed data against the schema is a good thing - as the data shouldn't never need to be migrated/transformed by further migrations.

This also prompted talks about bridging seed data away from migrations - they strive for two different purposes - discussing all the things that might entail, but migrations are an acceptable vehicle, for now, for seed data to travel on.
