### ISSUE TITLE
Add AWS credential filenames to the .gitignore template

### ISSUE THREAD

**Issue by gilmoreorless** [Prismatik/redbeard#133]
Because accidentally committing secrets is a Bad Thing™.

**Comment by MadRabbit** [comment]
hey @gilmoreorless could you please clarify which filenames did you have in mind?

**Comment by gilmoreorless** [comment]
There was a specific commit in another project that prompted this issue, I'll have to go find it to remember exactly.

**Comment by gilmoreorless** [comment]
@one19's suggested file list:

```
.env
aws_creds.env
cloudflare_creds.env
github_deploy_key.rsa
```

**Comment by MadRabbit** [comment]
gotcha, thanks!
