### ISSUE TITLE
Should PUT return 304 if no change in data?

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#136]
I'm not sure what the best way to handle this is, just throwing out a scenario I've encountered.

While testing I sent the same data (unchanged) through to an update route (`PUT /model/:id`) and an error was thrown:
```
err TypeError: Cannot read property 'new_val' of undefined
  hosportal_api_local |     at exports.firstChange.res (/opt/app/lib/rethinkdb.js:15:19)
```

This is due to there being no changes in data, and hence changes was returned as an empty array - so `res.changes[0]` is invalid at that point.

So my question - is it a valid use case to send through unchanged data to update?  It sounds crazy writing it, but even though I encountered this accidentally, perhaps we should return a `304 Not Modified`? (or another code, not sure of the best one to use here).  Would it be an error, or just a plain response?

If so, then perhaps we can add an error check in `.firstChange`, or somewhere, to catch this.

**Comment by davidbanham** [comment]
It should either be 304 or 200, but it definitely shouldn't be 500! Definitely need an error handler for that.

I think the issue with 304 is that according to the spec a 304 must not contain a response body. As the user of that API, my thought would be "Okay, great, I understand it didn't change but now I need to have a cache of the body I sent in order to populate my damn UI."

The intent of the PUT is "I want the data in the resource to look exactly like this body I'm sending." So long as it does, whether it was actually changed or not, I think a reasonable response to that is "Yeah, okay (200)".

**Comment by nwinch** [comment]
> I think the issue with 304 is that according to the spec a 304 must not contain a response body. As the user of that API, my thought would be "Okay, great, I understand it didn't change but now I need to have a cache of the body I sent in order to populate my damn UI."

That's true.  Though for our purposes considering our API client's usually have some kind of state management (mostly `redux` at this point), so returning nothing I don't think is a problem as you already have the data you just sent.  And I kind of like the fact that it would return a distinct code (`304`), as then I can check for that case in my code and do what's needed.  `200` would then mean you have to add a check to see if you got a response or not, but if it's `304` you know straight away you got nothin' back.

**Comment by MadRabbit** [comment]
i'd actually leave it 200. because as dave pointed 304 is not supposed to return data, and the way you normally consume apis in immutable world is something like so:

```js
ap.put('blah').then(updatedRecord => dispatch(updated(updatedRecord)));
```

if the API won't return any data then it will make communication with the API a bit more complicated than it has to be

**Comment by MadRabbit** [comment]
i feel like there is a consensus that it should return 200 as usual, so i'm closing this
