### ISSUE TITLE
Default auth error middleware isn't set up correctly

### ISSUE THREAD

**Issue by gilmoreorless** [Prismatik/redbeard#137]
Ref: https://github.com/Prismatik/redbeard/blob/425940c638ec8eb16816da740ffcac830f033c9f/base/index.mustache#L25

This is meant to be middleware that only handles errors, but it doesn't have the right function signature. According to the [Express docs](http://expressjs.com/en/guide/using-middleware.html#middleware.error-handling), error-handling middleware _must_ have 4 arguments.

The current signature with only 3 arguments has two detrimental effects:

1. The error-handling middleware is running for every request, not just those with errors. It's also checking for a `.name` property on request objects instead of errors.
2. Because it's not calling `next()`, any requests to non-defined routes just hang indefinitely, rather than returning with a 404.

**Comment by s-taylor** [comment]
Nath fixed this in Hosportal, probably worth talking to him about it.

**Comment by nwinch** [comment]
Yep.  See - https://github.com/Prismatik/hosportal/pull/55

Specifically file `/api/middleware/error.js`.

This should cover off the basics.  As an aside, we could also port `json` response support to `[kiss-my-error](https://github.com/Prismatik/kiss-my-error)` - @MadRabbit what are your thoughts on that?  Did you envisage that module becoming The Standard Way of Errors?  Be good to leverage off work that's already done.

Shouldn't take too much to patch it for multiple response types I don't imagine:
```
res.format({
  json: () => res.json(err),
  html: () => res.send(render(res, req))
});
```

Sumthin' along those lines, I guess.

If that wasn't meant to be it's purpose in life, we could probably bundle out this one from Hosportal and use that as a starting point and then adding`sentry` et al.

As another aside, errors should bubble up to middleware from routes, as currently they get caught too early:

This:
```
controller.update(req.body)
  .then(respond(res))
  .catch(errHandlerFactory(res));
```

Should be this:
```
controller.update(req.body)
  .then(respond(res))
  .catch(next);
```

This will..
1. Remove the need for the duplicated `errHandlerFactory`
2. Channel all errors through one central pipeline, for more concise logging (if logging exists)

**Comment by gilmoreorless** [comment]
Yeah, @lyntco has also been wondering about putting JSON responses into `kiss-my-error`

**Comment by MadRabbit** [comment]
yeah. we could add JSON support to kiss-my-error. i don't mind really; should be pretty trivial.

i believe that errors handling should be a shared package either way, kiss-my-error or not. it's such a routine thing. but we also need to consider proper integration with logging infrastructure, reporting, like sentry, and such. make it extendible for the customers when we hand it over, and so on.

so, this is important, but i reckon a quick patch to the existing solution by Nath would be the most pragmatic strategy in this situation. once we've sorted out bigger problems--such as models and controllers mess, then we can approach the errors handling and make it awesome.

**Comment by MadRabbit** [comment]
also, @nwinch is totally right about this:

> Should be this:
> controller.update(req.body)
>   .then(respond(res))
>   .catch(next);

**Comment by MadRabbit** [comment]
resolved in the `thinky` branch rework
