### ISSUE TITLE
Revision id doesn't change on update

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/redbeard#147]
I just noticed that I don't think the `revision id` is being changed after a user makes an update.
It's being generated and set on create but never changed after that.
Should be a simple fix to update the `.update` method in the model code.

**Comment by s-taylor** [comment]
I think this can be solved by updating the `ifRevMatches` function, see below (Object.assign... is the change I made). We should also add a test.
```
exports.ifRevMatches = update => {
  return doc => {
    return r.branch(
      doc('rev').eq(update.rev),
      Object.assign({}, update, { rev: uuid.v4() }),
      r.error('rev does not match')
    );
  };
};
```

**Comment by davidbanham** [comment]
Oof. That's a pretty boneheaded bug.

I _think_ that proposed fix will work, but the fact that it's running in the database context rather than the node context is fuzzing my brain a bit.

Definitely needs a test.

**Comment by MadRabbit** [comment]
yeah, i also saw this one. although why do we even have revs? it's not like we keep all the previous versions of the records. so why not use the more or less standard approach with an `updatedAt` field? it kind of the same thing and it can be used for practical purposes. also, `thinky` handles `createdAt`, `updatedAt` fields automatically

**Comment by davidbanham** [comment]
Yeah, that could be a great idea actually. We use revs because we're mimicking the CouchDB feature. I can't see a downside to doing the same kinds of checks on the updatedAt field.

It might produce confusing results if we got substantial clock drift between Rethink nodes, but so long as we're demanding exact matches of timestamps (same as rev) and not comparing them between one another we'll still be _safe_, it might just look weird looking at logs.

So this would mean we pull the updatedAt and createdAt fields into the model code, setting them in the database with `r.ISO8601(r.now())`

I can't actually find anything in Thinky that indicates it handles those fields natively. I'd also be (pleasantly!) surprised if it does the "error if it doesn't match" behaviour we're after.

**Comment by MadRabbit** [comment]
why do you want to match revs by the way? i feel like i'm missing something here. are you trying to implement the pull before you push strategy here like git does?

just wondering why do you want it a generic case. i mean there are obviously cases when you need that, but as a generic solution this could be a massive PITA to work with from the client side.

**Comment by davidbanham** [comment]
Original discussion on that is here:

https://github.com/Prismatik/redbeard/pull/90#issuecomment-218362765

The crux is:

> 
> Alice and Bob are surgeons. They both fetch `/shifts/foo` at 1pm.
> 
> It's a great shift! They both want it.
> 
> At 1:01pm, Alice presses the "Take Shift" button. Her browser modifies the document to read `owner: 'Alice'` and POSTs it back to the API. She gets a 200 and her browser says "Congratulations! That shift is all yours!"
> 
> At 1:02pm, Bob presses the "Take Shift" button. His browser modifies the document to read `owner: 'Bob'` and POSTs it back to the API. The API sees nothing wrong with his request and saves the document, returning him a 200. His browser says "Congratulations! That shift is all yours!"
> 
> Alice and Bob both show up to the same operating theatre and a vicious scalpel fight ensues. The patient bleeds out on the table.

In my experience it places 0 overhead on the client. You fetch a document from the API, you make some changes to it, you POST it back. If you're doing so much weird stuff to the document that you have to recreate it from its fragments and it's a burden to remember to put the rev back in place, you're probably doing something else wrong. There's never been a time in building apps on Couch that I've found it to be a problem.

You definitely shouldn't be "pulling before push" to satisfy the rev constraint. The rev matching step, and associated failure, is an opportunity to say to your user "Hey, the world changed while you weren't looking. It now looks like _this_. Do you still want to make it look like _that_ or do you want to make some different choices in light of this information?"

It's not necessarily required on every single route/document in the history of whatever. It's required on any one of them that might possibly be accessed by two consumers simultaneously. The frequency of that is high enough, and the burden of including it is minimal enough, that it makes sense to Just Do It.

**Comment by MadRabbit** [comment]
yup, i got that. the collisions like that can be a problem. but it feels that it is not a generic enough issue to make _all_ models behave this way.

i think this is a specific problem that should be fixed in two steps:

1) web-sockets to make the UI to reflect the changes immediately
2) additional server side logic that check the rev or updatedAt to make sure that unintended collisions don't happen

making it a generic implementation i think will be a problem more often than not. in most cases you don't care about those collisions, and dragging that `rev` around can be unnecessary pain on the client side that will slow everything down.

so, in this light i think `rev` should be an explicit `rev` as it is a specific business logic case and i don't see a reason to obfuscate the problem with updatedAt markers. but, i also think it should be optional and only enabled where the business case requires to do so.

**Comment by davidbanham** [comment]
> making it a generic implementation i think will be a problem more often than not. in most cases you don't care about those collisions, and dragging that rev around can be unnecessary pain on the client side that will slow everything down.

I've been using revs for years and I haven't felt that pain. Can you elaborate on potential pitfalls you're seeing?

> so, in this light i think rev should be an explicit rev as it is a specific business logic case and i don't see a reason to obfuscate the problem with updatedAt markers. but, i also think it should be optional and only enabled where the business case requires to do so.

We _could_ make it a --flag to the generator but I think that'd be a bad idea. Too likely that you realise you need it only a few months down the road.

We could also make it a boolean arg to the `new Model()` constructor. That's probably fine but putting conditionals in that logic is going to clutter things up.

I think what I keep coming back to though is that in my experience it's just not a thing to worry about. Having it on every document makes things more safe, without actually making it any less convenient to use. Why not?

**Comment by MadRabbit** [comment]
Ok, let me try another angle. How do you feel if the `rev`s will be backed into `Model`? it will know how to validate rev diffs on update and how to create/replace the markers automatically on create/save. Kind of like `createdAt` and `updatedAt` timestamps

**Comment by davidbanham** [comment]
I'm not fussed whereabouts the logic lives, so long as it gets executed within the database at the time of committing the document, and so long as the rev remains with the data at all times. Anything else leaves it open to a race condition.

**Comment by nwinch** [comment]
> Anything else leaves it open to a race condition.

True.  We had the very real possibility of this happening on Hosportal.  Even with websockets there's no definitive reliability of race conditions not happening unless the `rev` tags along for the ride with all the other data.

TBH it still does feel heavy-handed for the client-side - and to try and elaborate on that, I guess it feels unnecessary that the client-side has to care about this data for the rare case that things may get out of sync; so you're left adding in hidden input fields which use the `rev` to be submitted with document updates etc.. but there doesn't seem to be other alternative methods that can do a more reliable job.  I kinda just got use to factoring it in the client-side I guess :)

> We could make it a --flag to the generator but I think that'd be a bad idea. Too likely that you realise you need it only a few months down the road.
I agree.  I think once a project starts to scale quickly you'd probably end up ruing that you didn't run with it in the beginning.  There's also a confidence factor that it provides - I know this definitely will solve the issue, and it's not something I'll have to worry about when we go from 100 to 100,000 users.

**Comment by davidbanham** [comment]
> so you're left adding in hidden input fields which use the rev
That should get simpler once we've got the UI project up and running.

**Comment by nwinch** [comment]
Yep, modularising the form functionality should help a lot with that.

**Comment by s-taylor** [comment]
A related issue is here https://github.com/Prismatik/redbeard/issues/162

**Comment by MadRabbit** [comment]
this is closed by https://github.com/Prismatik/redbeard/pull/177
