### ISSUE TITLE
ENV vars initialization

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#148]
It's a bit in a disarray at the moment, part of it lives in the `test/helper`, part in `src/server`. it all should be in one place in `config/env`

**Comment by davidbanham** [comment]
Shouldn't it be happening in `.env` rather than `config/env`?

**Comment by MadRabbit** [comment]
i think `config/env` should pull `.env` in. basically the idea is that `config/env` incapsulates the ENV vars processing logic and exports the cleaned and good to go vars as a hash. then the application code doesn't refer to `process.env` anymore and uses the processed and normalized props from the config, something like that:

```js
// config/index.js
Object.assign(module.exports, require('./env');

// config/env.js
const envHanler = require('some-env-stuff');
module.exports = envHandler(process.env); // <- explode here on missing vars and stuff

// some application code
const { SOME_VAR, ANOTHER_VAR } = require('../config');
```

this way we can retain the original `process.env` data and, at the same time decouple the configuration management from the application logic

**Comment by davidbanham** [comment]
Ah, okay. So would this get you what you're after?

```
// config/env.js
const dotenv = require('dotenv-safe');
dotenv.load();
module.exports = dotenv.parse(fs.readFileSync('../.env')); // This could be made prettier by dotenv-safe returning the variables it actually parsed. If we just export the entire process.env it runs the risk of overwriting stuff unexpectedly

// config/index.js
Object.assign(module.exports, require('./env');

// some application code
const { SOME_VAR } = require('../config');
```

**Comment by MadRabbit** [comment]
yup. if there are any required ENV vars the `config/env.js` script should explode if they're missing

**Comment by davidbanham** [comment]
Yep, dotenv-safe will asplode if anything in example.env isn't defined in .env
