### ISSUE TITLE
PUT vs PATCH

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#149]
So, at the moment we're using PUT as basically PATCH, meaning that PUT takes partial model updates. this is a good pragmatic approach, but it is not exactly consistent with the HTTP protocol. after a talk with @davidbanham we've decided that this needs to be changed. and sooner than later.

the outcome is PUT should accept only full documents and replace the document completely. and PATCH should take partials and save them on the model.

**Comment by davidbanham** [comment]
:+1:

**Comment by MadRabbit** [comment]
i believe this is resolved in https://github.com/Prismatik/redbeard/pull/171
