### ISSUE TITLE
Move web-sockets into a separate generator

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#150]
We've generated 15 models for shortlyster and none of them so far needed web-sockets. Eventually one of those potentially might need them, but otherwise it's just dead code sitting in the repo, doing nothing. And I reckon hosportal has a similar story.

This should be moved out and used only when and where needed

**Comment by davidbanham** [comment]
That places additional cognitive load on the API consumer. You constantly need to be asking the question "Does _this_ one expose a websocket API or do I need to go generate it?"

It also makes it much more difficult to develop generic tooling (like RB-Admin) if the API surface area isn't uniform.

**Comment by MadRabbit** [comment]
i think it's the other way around. the cognitive load is definitely there and it is "what's this code doing in my repo? is it attached to anything?"

afaik web-sockets is not a part of any JSON API standard, not even a half-standard, it's just a thing we do locally here at prismatik. Because RB-Admin, which is again is not used by anyone, even locally. as such, I don't think we should propagate this as a standard addition to every resource we expose.

even if you want to force it in as a home grown standard, i think it should be an opt-in feature. all the confusion with whether a resource supports sockets or not can be very easily handled via other tools, like documentation and manifests. our awesome JSON APIs will eventually have documentation won't they?

**Comment by MadRabbit** [comment]
also, regarding RB-Admin. I think it is a pretty generous stretch to use it as a use case. I know the "if someone else added a record" argument and I think this is a non existing problem at this point. It never happened and if it did, the problem could be resolved in a second via normal page refresh and updating the record via a standard CRUD interface.

i don't see why we should spend days of development time, and more development days on dragging this feature everywhere, when a problem could be solved in a second with Ctrl+R. to my view it is a burden and i don't want everyone to drag this ballast around unless it's actually required by business requirements of a client

**Comment by davidbanham** [comment]
No, it's not part of any JSON API standard. Yes, this is something we've developed locally because it's useful to us. We certainly would be using RB Admin locally but it needs some work to bring it up to date.

Obviously the APIs will have documentation. Ideally, I would like the bulk of that task to be handled via automatic generation. That's a simpler task where the surface areas are uniform.

**Comment by MadRabbit** [comment]
ok, after talking to Dave and thinking about the long term goal, i think sockets can stay in by default if we fold and generalize the routes and tests implementation so that we didn't have dead unmaintainable code in database. generic builders and tests can be updated certralizingly (you heard it first here) and i'm okay with this

**Comment by davidbanham** [comment]
I think the key is to make the burden of maintaining those tests low enough that it's eclipsed by the benefit of having a standard API. If we can't get that smooth and seamless enough, then we should make it optional. Let's take that moonshot, though!

**Comment by MadRabbit** [comment]
i'm closing this as per the discussion in favor of the standard API
