### ISSUE TITLE
Fold routes with a routes creator

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#151]
Most routers are uniform and pretty much the same, so we should fold them with a routers creator, the same way we did with the controllers. Something like this:

```js
const router = buildStandardRouter(controller);
```

**Comment by davidbanham** [comment]
:+1:

We're getting tantalisingly close to where these utils will have a stable enough API that it will make sense to shuffle them out into separate modules.

**Comment by MadRabbit** [comment]
yup, that's my plan. to create a separate module that has all the fancy features in them, which we can then just bolt on top of actual application and schemas
