### ISSUE TITLE
Migrations are busted since the Thinky refactor

### ISSUE THREAD

**Issue by davidbanham** [Prismatik/redbeard#154]

**Comment by s-taylor** [comment]
@davidbanham so for migrations do we want to use thinky? I'm thinky no? We basically just want to directly access the database to bypass any schemas right?

I also noticed this is devoid of any documentation so I'll try add some to make it clearer.

**Comment by davidbanham** [comment]
Deffo want to bypass schemas. The basic mechanism we had in place is correct, it's just that things got jostled around a little and now the pipes aren't quite hooked together right.

**Comment by s-taylor** [comment]
Cool, so far it seems to be just incorrect paths which I've updated. Figured out how to access rethinkdbdash via thinky as well so that's solved. Just need to check the auto migration stuff still works as well.

**Comment by s-taylor** [comment]
Resolved in https://github.com/Prismatik/redbeard/pull/166
