### ISSUE TITLE
Add seed data functions

### ISSUE THREAD

**Issue by davidbanham** [Prismatik/redbeard#155]
We've built these out in a couple projects now. Would be good to get them back into mainline

**Comment by nwinch** [comment]
How we implemented it on Hosportal worked pretty well.  We didn't experience any issues.

We used the migrations vehicle to perform seeding, but from early discussions, this never felt quite right to use migrations for two different things, and was really a side effect of not having enough time to implement something else.

A cleaner separation of concerns could be to have a separate `/bin/seed` script which could then use a slightly genericised version of migrations lib to shoehorn data from `/seed/users_whatever.js` in to the DB.  That way you wouldn't need an env var for seed data - which is a bit flaky in the case that you forget to add it to a migration script - and instead would just trigger `/bin/seed` on the server environment that wanted to use it - I guess with Docker or whatever - and then migration files could be left alone to truly be actual migration of data.

**Comment by gilmoreorless** [comment]
> A cleaner separation of concerns could be to have a separate /bin/seed script which could then use a slightly genericised version of migrations lib to shoehorn data from /seed/users_whatever.js in to the DB.

That's what we did for SL after the Thinky rebuild.
