### ISSUE TITLE
Build analytics

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#161]
As we add/remove/upgrade redbeard, we should have some way of tracking what works, and what doesn't.  I don't see this as a code thing, but also don't see it as an "debate and agree on github" thing either.  Let my try and explain my thoughts.

For example, Prismatik adds a new way to build controllers for redbeard.  We're happy with it, and we think this is the right way forward for all projects.

But, the next 3 projects using redbeard decide to refactor away from using controllers that way.  For whatever reason(s), it just doesn't work.  So it would stand to reason that we would then change redbeard to suit how we like to do things.  We now have data that our intended architecture does not match how we actually do things.  This is important data.

This would be a chance to compare the the design of redbeard (how we intend to use it) against the UX of redbeard (how developers are actually using it).

I think this information could be valuable for us to help prioritise on what is important to iterate on for redbeard.

Perhaps this might be a Nikolay or Dave thing to head up, but after each project that uses redbeard is completed, there is a post-mortem on if/how/why we deviated away from the original intentions of redbeard eg. use routes this way, do migrations like this, secure your endpoints like this etc.. and does that new way of doing things actually work better?  Was it consistent with the other recent redbeard projects?  Is there a new trend emerging for us to take notice of?

Thoughts?

**Comment by davidbanham** [comment]
Agreed. That kind of introspection is built into Nikolay's JD. I'll leave it to him to chime in on how he plans to manage it.

**Comment by MadRabbit** [comment]
we were supposed to run analytics on all our projects, but before i stepped in, someone decided to run multiple projects in the github repo, which basically rendered the analytics pretty useless. i'm collecting data on `redbeard` itself, but not much on the actual projects.

my strategy at this point is to wait for the next project to start and then set it up properly in multiple repos so we could track metrics cleanly, see growth dynamics and stuff

**Comment by nwinch** [comment]
I think you misunderstood my suggestion, let me try and clarify.  I'm not talking about code analytics, but rather, how we collate the heuristics of redbeard projects and what insights we can gather from that to decide what features we should update/add/remove from the redbeard core.

For example, after both hosportal and shortlyster finish, they might both have forgotten password features.  So we might decide that that is something we should bundle out into a separate package so it can be reused again - we shouldn't need to create this package, but we can use the code already written.

So we are letting our known practices and data drive the features for redbeard, as opposed to things that we think are just "good ideas".

Does that make sense?

> run multiple projects in the github repo

This is a good thing, and was actively decided by the team.  We had established on previous projects that time cost and context switching of running multiple repos - just in the beginning of a project, while itself together - was not worth it, so putting both api/client in the same repo has become a real time saver, and has been working well so far.

**Comment by MadRabbit** [comment]
right, yeah, i think i thought a different thing. i guess what you're talking about will be a part of the building strategy in general. in the end redbeard is not about building things the _right_ way, more about having our own flavour of the right way. something that is based on best practices, but adjusted to our own reality.

again it's a balance between how we do things and how other people do it. one one side we need to adhere to best practices outside of prismatik, on the other hand we need to have routine things decided and sorted out, so we that we stopped spending time chasing different ends of a spectrum. if that makes sense.

said that, i think we should have post-mortems after all projects and talk things through, like what worked, what didn't and what could be improved. and then feed that back into the redbeard projects. i know know about _analytics_ per se, but the build - measure - learn loop definitely will be part of the development process

**Comment by MadRabbit** [comment]
as there appears to be no further discussion, i'm closing this down in favor of having retros on development experience with redbeard, which I suggest we hold at dev monthly meetings
