### ISSUE TITLE
"definitions" schema returned via /schema

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#163]
I think the `/schema` endpoint should probably just be returning resource specific schemas, unless this is by design?

**Comment by MadRabbit** [comment]
yeah, i agreed, schemas should be just normalized by default

**Comment by davidbanham** [comment]
They are normalised by default, but the definitions schema tags along for the ride. I don't think it would break anything to chomp it off before sending the response to `/schemas` but equally I don't think it's doing any harm in being there.

**Comment by nwinch** [comment]
It's doing harm over in `redbeard-admin` as it's not in the same format as the other schema files.  This could also affect other projects that want to check `/schemas` and make the assumption that you're getting resource schemas.

So far, I think only `redbeard-admin` is actively using `/schemas` endpoint for things?  Not any redbeard projects?

I think it makes sense to remove it so there's a clean export of just resource schemas

**Comment by MadRabbit** [comment]
makes perfect sense. i'll slot it for fixing
