### ISSUE TITLE
Naming for command line options

### ISSUE THREAD

**Issue by Nicktho** [Prismatik/redbeard#17]
While working on the new naming conventions branch, `redbeard controller X` doesn't feel right anymore. The command spits out routes, a controller, a model and a schema.

I suggest we switch the name to `resource`. This, in the future, allows us to reserve `controller` for more fine grain generation of files, eg: `controller` spits out just the controller, `model` spits out just the model, etc.

**Comment by davidbanham** [comment]
:+1:

**Comment by nwinch** [comment]
Related #2
