### ISSUE TITLE
Split controller code into lib

### ISSUE THREAD

**Issue by davidbanham** [Prismatik/redbeard#3]
The idea of keeping all code within the controller was great initially, but it's gotten out of hand. Let's see what we can pare out of the controller template into a controller helper lib.

The first 65 lines of defined functions are an easy win.

There's also the potential to extract some of the code within the exported functions. We want to tread a fine line there between reducing noise, yet retaining flexibility to insert resource-specific business logic.

**Comment by nwinch** [comment]
Done with #10
