### ISSUE TITLE
Before/After/Each with Tape

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#32]
@davidbanham This todo..
> Potentially use a before/after/each plugin for Tape

Before/after is fairly trivial:
```
function beforeAfter(description, cb) {
  test(description, (t) => {
    // before promise
    someKindaPromise.then(thing => {
      cb(t).then(() => {
        // after promise
      });
    });
  });
}
```

Can easily split that up if both aren't needed, but the bones are there.  I'm sure I was making a repo for some `tape` utils some time ago.. must've not finished it.  I'll see if I can dig it up.

> ... or just switch to Mocha

I'd vote Mocha, but `tape` is pretty well stuck in there now..

**Comment by davidbanham** [comment]
If we want to get away from tape now is the time to do it. It's still a pretty straightforward process.

I think the main criteria for the decision is "If people want to use our thing and they see that means being tied to tape, will they be cool with it or run away?"

**Comment by nwinch** [comment]
How do we answer that?  Internally we can poll mocha vs tape usage, give opinions, but not sure how we'd answer that question directly, other than mapping our own data loosely on to the community to make an assumption?

**Comment by davidbanham** [comment]
I think we need to answer this qualitatively rather than quantitatively.

We could, though, look at the number of things that depend on Tape vs the things that depend on Mocha and decide whether the gulf is so vast that it's an obvious choice.

**Comment by MadRabbit** [comment]
oh, i've just noticed the thread. i've posted a new issue #37 about mocha. and that is one of the things why i prefer mocha over tape. it's so much more practical with this sort of things

**Comment by nwinch** [comment]
I'll close this as the "before/after" issue part has been answered, and we can continue Tape vs Mocha in #37.
