### ISSUE TITLE
Implement express-jwt

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#36]
I've noticed you do JWT handling manually in a custom middleware. did you consider https://www.npmjs.com/package/restify-jwt ? it's kind of the same thing as `express-jwt`

**Comment by nwinch** [comment]
Yeah using the middleware makes sense to me.

**Comment by davidbanham** [comment]
Yep. Using the middleware would make the route matching/missing stuff neater than the "I dunno, expand this if condition" that I've got in there at the moment. In light of #64 though I'm changing the name of the ticket.

**Comment by davidbanham** [comment]
This ticket is now to implement https://www.npmjs.com/package/express-jwt

**Comment by davidbanham** [comment]
This also intersects with #4

**Comment by MadRabbit** [comment]
Makes sense, thanks!

And just for the future record, the app currently uses the 'jwt=' query param to receive tokens, which is a serious security concern as all the tokens will end up in the server logs in plain sight.

Thus must be reworked to accept http headers only

**Comment by nwinch** [comment]
Resolved by #80
