### ISSUE TITLE
Which async control flow?

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#38]
Did you know that if you'd use mocha and generators with async control flow, your controllers tests could be so much cleaner and easier to extend and maintain. here's an example

https://github.com/Prismatik/opensourcify/blob/master/test/routes/github_test.js

**Comment by nwinch** [comment]
We've used generators extensively on [Ordermentum](https://github.com/Prismatik/btq-projectw), so yep, we did know :)

We could broaden this question to "What async flow does Redbeard pursue?" as I don't think it just applies to tests.  Currently I see a mix of callbacks and promises around town.  It would be convenient to stick to one eg. Callbacks vs Promises vs Generators.. and continue that trend throughout the code base.

I'll edit the issue description.

**Comment by nwinch** [comment]
Related #50

**Comment by MadRabbit** [comment]
I see. As far as my personal preference goes those days, for the server side i prefer

1. Generators
2. async/await
30. Promises
31. Callbacks

Generators are generally easy to hammer in on the node side. not sure if restify supports them, although it is trivial to add support. Async/await is a more solid solution, but requires babel and transplitting.

Promises are okay, but they are a marginal improvement over callbacks in my mind. On the other hand, without async/await you will end up writing promises either way, so you could consume them in generators.

**Comment by nwinch** [comment]
+1 for promises + generators.

**Comment by Nicktho** [comment]
I suggest we don't use or even consider async/await until it is stage 4.

I'd prefer promises, I've raised my concerns for why using generators for async control flow might not be the best idea in the developer chat, but in summary:

Using generators as async control flow requires wrapping each generator in a function that continuously asks for the next value and gives it the old one resolved, expecting each to be a promise, essentially looping itself. It works, it's valid javascript, although I consider it an abuse of the concept. As a newbie, I found myself confused when first hitting generators in our projects used this way.

One of the goals of redbeard is to be accessible and usable by as broad of a developer base as possible. I rarely see generators for control flow in popular libraries, whereas promises have become the "go to" for dealing with async.

Switching tape to mocha as per issue #50 will clean up the tests significantly, and libraries such as https://github.com/domenic/chai-as-promised exist to help deal with assertions on promises.

I'm +1 promises, -1 generators.

**Comment by nwinch** [comment]
Fair point on generators.  We're aligned on promises so far.

**Comment by MadRabbit** [comment]
@Nicktho that's a great point that not that many projects use generators. more of that, they were confusing to me at the beginning as well. took me several attempts before they clicked.

i think there are two main reasons why generator are not widely adopted: 

1. they are confusing and can be a challenging at first
2. everyone either just waits for async/await instead or just uses babel

I don't want to press hard on this, as I can live with both of them just fine. But, i find that generators and async/await clear up async control flow significantly. The final code is so much less confusing than a Promises equivalent that I use it almost everywhere where i can.

Depending on how much you value clarity of code, the wins might worth the effort

**Comment by s-taylor** [comment]
I'm a big fan of generators, I think it makes code easier to write and easier to read and it's nicely compatible with promises. But that said I also don't want redbeard's adoption to be hurt by using something the community is not familiar with so if promises are king I think that's a better choice for now.

**Comment by davidbanham** [comment]
I completely agree that async/await is the future, and that generators are a surprisingly fine fill-in until they arrive. I'm happy for us to use generators or babelled async/await in our internal stuff. The Harvester project proved to me that the simplification of code that it results in is significant. However, I think choosing either of those options now would be too far outside the mainstream for Redbeard.

I think we should standardise on promises until either:

1) Generators for control flow become substantially widespread
2) Async/await finally hits stage 4/lands in node.

**Comment by MadRabbit** [comment]
resolved in the `thinky` branch in favour of the ES6 generators and rainbows
