### ISSUE TITLE
fixtures are bing generated outside of the test folder

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#39]
should be really under the `test/` folder in my opinion

**Comment by nwinch** [comment]
Where exactly?  Are you referring to `./test.js` not being in `/test` ?

**Comment by MadRabbit** [comment]
at the moment it is just `fixtures/`, i think it should be `test/fixtures/`

this probably should be part of https://github.com/Prismatik/redbeard/issues/45

**Comment by davidbanham** [comment]
Fixtures can be useful for more than just testing. You could happily use a fixture to auto-populate documentation or pre-fill client forms, for example.

**Comment by MadRabbit** [comment]
that is a good point and i agree. but on the other hand, lets think about it a bit more. how often do you need fixtures for tests and how often do you need them for other purposes? shouldn't they belong to where they're used more?

Besides, i'm not suggesting to move them to another repo, it's just a different folder; still perfectly accessible within a project

**Comment by davidbanham** [comment]
Nesting under the tests directory implies that they're owned by the tests, though. eg that their dependencies should be considered dev deps or that their functionality can be interleaved with test library code.

I don't see a significant disadvantage in leaving them in the top level dir. Is it just clutter we're worried  about or something more?

**Comment by nwinch** [comment]
> Nesting under the tests directory implies that they're owned by the tests, though. eg that their dependencies should be considered dev deps or that their functionality can be interleaved with test library code.

I would skew use this as a point in favour of having them nested.

Testing is what fixtures are bred for.  Are there any other purposes you would want them for?  If you find yourself having ideas of using fixtures for other areas of the app, then they would probably warrant repurposing as a `lib`, or `resource` IMO.

Less clutter is one advantage.  Having all test related code in one area seems polite.  On the flip-side, I don't see any advantage of having them at top level?  Given that all our other projects use `./test/fixtures`, I think it would be reasonable to not buck that trend now.

**Comment by MadRabbit** [comment]
yup, pretty much what Nathan said. `test/fixtures` is the least surprising place for them to be.

also, if you're using fixtures for something else than tests is kind of like trying to shot two rabbits with one shot. one of the reasons to have fixtures defined in tests is that it helps to express and control the surface area of modules. so in tests fixtures not necessarily should be full spec objects, sometimes it makes more sense to limit them to indicate the surface area of a specific piece of code; while fixtures built for seeding purposes must be full size blobs of data. if you're reusing them on both sides the end result will be mediocre for one of them

**Comment by davidbanham** [comment]
I'm not too fussed about this. Happy for them to move into the `test` dir if we think it'll make the structure less surprising.

**Comment by MadRabbit** [comment]
resolved in the `thinky` branch
