### ISSUE TITLE
Add special User model type with signin, signout & password reset

### ISSUE THREAD

**Issue by Nicktho** [Prismatik/redbeard#4]
First steps:

• Sign up
• Sign in / Sign out with token auth
• Password reset

Extras

• Middleware that authenticates auth token and returns current user to controller or handles request with a 403 if authentication fails
• Emails for sign up and pw reset

**Comment by nwinch** [comment]
@Nicktho I vaguely remember you started work on this - where did this end up?  Any work on a branch that you can tag here?

**Comment by MadRabbit** [comment]
Maybe we should consider using a third party package here? It's very repeateable task and a cost of failure, because you didn't know or just missed something is quite high.

**Comment by nwinch** [comment]
Resolved by #69
