### ISSUE TITLE
controllers vs routes split

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#40]
The way controllers and routes are split don't make much sense to me and feel quite non-standard to be honest.

It feels like your controllers are more like a services layer, but they also barge into actual action controllers field. and then your routes are very repetitive and offload a lot of things they should do into what you call controllers.

i most modern projects i see and have been working on the structure is that routes mostly play the role of controllers that handle the HTTP data and responses. routes talk to services or models directly. that's why Express even has `Route` so you could build them independently and then mount to each other in any way you like.

a lot of porjects in node don't even have a thing called `controllers`, they just do very DRY `routes` and then there are models and if things get out of hands then there are also either `services` or `utils` depending on the nature of a project. a normal structure would be like so:

```
src/
  middleware/
  models/
  services/
  routes/
  app.js - the app without HTTP server
  server.js - the HTTP server that boots the app
test/
  middleware/
  models/
  services/
  routes/
```

Your structure seems heavily skewed towards controllers/services. You kind of have empty rudimentary models and routes, but then ended up with a bucked labeled `controllers` where you dump pretty much everything else. That's not gonna scale that well.

Also if you have noticed it led you to pretty chunky controller tests that also test routes as well. and the result you don't have routes tests at all. In a normal scenario, your `routes` tests would be your integration tests and middleware / models / services will contain unit tests for critical parts

**Comment by nwinch** [comment]
@MadRabbit I'm going to close this as this layout/naming discussion has been started (and looks like there was an _almost_ result for change) over in #2 a while back.  Let's continue there.

**Comment by MadRabbit** [comment]
@nwinch i thought about this a bit, and think this shouldn't be closed, this a bit different from the naming convention issue.

the problem here is the app architecture in general, not the naming per se.

the problem that i'm trying to highlight here is a tight coupling between what you call `controllers` and what you call `routes`. Normally `controllers` should not know anything about the `req`, `res` or any HTTP related things at all.

The idea is that every layer in the app should handle a specific domain area and they should not overlap

`routes` - do the HTTP thing and handle req -> res
`controllers` - handle the business logic, you don't even need this to be shaped as a CRUD layer
`models` - define the data structures and interact with the persistence layer

`controllers` are not the CRUD controllers we know and love in rails. `controllers` is the business logic, depending on a case it might have things like `thingCreator`, `stuffNotifier`, `dataAggregator` and so on. the actual CRUD interface is part of the HTTP vocabulary and should be isolated in the `routes`. that is why i suggested to name it `services` instead of `controllers` in #2 to avoid confusion in the purpose.

i'm not sure if i'm making the problem clear here /cc @davidbanham @Nicktho
