### ISSUE TITLE
strict mode

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#42]
I've noticed that none of the auto-generated files have the `"use strict";` marker in them. as we don't use any precompilers for the source code in here, this might lead to very annoying issues with block scope variables now and then. this can be avoided

**Comment by Nicktho** [comment]
I suggest we either

1. Babel the thing with the es2015 preset.
2. Pick a node version and stick with what is supported without strict mode enabled.

**Comment by davidbanham** [comment]
Why is using strict mode but no babel not an option? Legit question, I dunno.

**Comment by MadRabbit** [comment]
closing this as we're like in node 6 world and stuff now
