### ISSUE TITLE
Scripts should go in a bin/ folder

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#43]
i've noticed there is a whole bunch of scripts hanging in the root level of a project. that is a pretty crowded place, i think they should go into a `bin/` folder or something

**Comment by nwinch** [comment]
+1

**Comment by davidbanham** [comment]
Huh? The only scripts I'm aware of are the migration ones and they're in `/bin`. Which ones are you seeing?

**Comment by nwinch** [comment]
For `./base`, I think `index.js` could be moved to `./bin`.  I prefer that all entry point scripts - web or otherwise - be `bin`'d.  Keeping root level as uncluttered as possible is ideal, with the exception of configs and their ilk.

**Comment by davidbanham** [comment]
Right, that makes more sense. I thought we were talking about executable files, since that's what I expect to find in a directory named `bin`. I'm happy to move index.js etc into `/bin` if it'll put smiles on dials.

**Comment by MadRabbit** [comment]
in the `thinky` branch i've extracted the http server piece into the `src/server.js` file. i think it makes sense to move it into a proper `bin/www` file, as that's where it should be living
