### ISSUE TITLE
.env file 

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#44]
I've noticed that you hardcoded env vars into the autogenerated `package.json`. You kind of encouraging devs to put more in there.

I recon this should be solved in a more standard way by using standard confirguration and `.env` files support

**Comment by davidbanham** [comment]
100% agree. This was done before you and I had that discussion. The thing we agree was that:

There should be a default `.env` file for developers developing locally. It should be called `example.env` or something snappier.
`.env` should never be committed into source control, lest it leak into production and release the four horsemen of the apocalypse.

**Comment by nwinch** [comment]
Resolved by #77
