### ISSUE TITLE
Generated project structure

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#45]
I've noticed this at other prismatik projects as well, the folders structure is a bit off the beam. It basically looks somewhat like this:

```
env/ <- configs
lib/ <- more configs
routes/
src/models
tests/
```

Imho we could improve coherence if we follow a structure like this one:

```
bin/
  ... project specific scripts if needed
config/
  .. all configs
  index.js <- exports all configs

src/
  middleware/
    ... all middleware
  models/
    ... models
    index.js <- exports all models
  services/
    ... contains various business logic services
  routes/
    ... route handlers (one per resource)
    index.js has all the routes mounted together into one middleware
  app.js <- the app (without the server) just middleware routes bolted together
  server.js <- the HTTP server that boots the `app` on `PORT`
test/
  middleare/
     ... unit tests
  models/
    ... unit tests
  services/
    ... unit tests
  routes/
    ... integration tests for the app
  fixtures/
    ... all the fixtures
  helper.js <- the test env setup and configs/patches
```

I've seen a structure like that in many projects and scales very well. it leaves space for all sorts of things and you mostly know what goes where.

It is also very easy to navigate and match code with tests

**Comment by Nicktho** [comment]
So much +1

**Comment by nwinch** [comment]
I agree with `/config` over `/env`.

`/src` makes sense for projects where you are actually building from `/src` to a `/dist` folder or similar, though not for projects where that isn't the case.  No need to go one folder deep if not necessary, and you can leave `models`, `lib` etc.. all at root level.

**Comment by MadRabbit** [comment]
@nwinch the reason you want all models, routes and stuff under one folder is that you will end up with a symmetric structure in the `test/` folder. this way it is much easier to flip between code and tests, there are even plugins for editors that do that. it is a convention and a good practice that carried over from a language to language. you just know immediately what's where.

also, the root level is usually a crowded place, there is `config/`, there is `bin/` there are `migrations/`, `logs`, `tmp`, `docs` etc. etc. so having a dedicated place where you could say "here is where all the code lives", "here is where all the tests live" makes sense and gives a hint to the future developers where everything should go.

as for `src` vs. `lib`, i'm fine either way. but, i'm personally trying not to use `lib` for two reasons: firstly, `lib` was historically it was used for "shared libraries", basically what `node_modules` is for. it's not for the main application code, but for things that can be reused between projects. and secondly: when you switch between projects that transpile and those that don't having it named consistently helps. a bit.

**Comment by nwinch** [comment]
The alignment between `/src` and `/test` makes sense.  If I think hard and squint my eyes, I'd say my main gripe would you've got to prefix `src` in all your import/requires.  This could be solved with a symlink I guess, and/or using relative paths but that's a different kind of messiness ;)

But yep, I'd generally be happy for things to go in `/src`.

**Comment by nwinch** [comment]
Re `src` vs `lib` - I prefer `src`.  `lib`'s meaning is already taken in my opinion.

**Comment by MadRabbit** [comment]
do i understand correctly that we are aligned on this? can i make the change?

**Comment by MadRabbit** [comment]
@nwinch @davidbanham are on the same page with this one? i feel that this also should go in rather sooner than later

**Comment by nwinch** [comment]
The outlined structure makes sense to me.

**Comment by davidbanham** [comment]
In my mind `lib` is a halfway house between `src` and `node_modules`. It's for things designed to be used by multiple parts of the code within this project, but not genericly useful enough to make sense to other projects. Project-specific helper functions, basically. I do have a tendency to let too much stuff slop in there during times of concerted effort, though.

`src` in the top level for non-compiled projects feels a little weird to me, too, but I'm happy with Nikolay's rationale. Root is only getting more crowded with CI configs, docker configs, etc. Let's run with `src` as Nikolay laid it out.

So in light of that I think any project specific helper libs (as and when they exist) should be in `src/lib/`

**Comment by MadRabbit** [comment]
resolved in the `thinky` branch rework
