### ISSUE TITLE
Update test framework - replace Tape with Mocha

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#50]
As [per this discussion](https://github.com/Prismatik/redbeard/issues/37), we are moving to Mocha.  Closes #37.

**Comment by MadRabbit** [comment]
this is blocked by #48 discussion

**Comment by nwinch** [comment]
As far discussions go, I think this can now move forward with a measure of reliability that Mocha/Must is the choice?

**Comment by MadRabbit** [comment]
yup, seems that we agreed on mocha + must and fluent assertions as the basis. lets leave it at that.

**Comment by davidbanham** [comment]
I don't think this is blocked by #48 at all. Mocha is the choice for the test harness. Whether we also change the assertion library can happen in the future too. It's not like Mocha is incompatible with any of the assertion styles or libs we're talking about.

**Comment by MadRabbit** [comment]
resolved by #68
