### ISSUE TITLE
Optimise orderBy using indexes

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/redbeard#56]
Right now orderBy is not using our indexes.
We're using `.orderBy('date')` in all cases rather than `.orderBy({index: 'date'})` when an index exists.
We should optimise our query based on if the field requested to use orderBy is indexed or not (which is now identified in our schema).

https://www.rethinkdb.com/api/javascript/order_by/

**Comment by MadRabbit** [comment]
i think the correct syntax is `.orderBy(name, {index: 'blah'})`

**Comment by nwinch** [comment]
Resolved by #67
