### ISSUE TITLE
Redbeard folder structure should match the generated code structure

### ISSUE THREAD

**Issue by s-taylor** [Prismatik/redbeard#58]
`controller.mustache` file is at the root level (inside the controller folder) but ends up in `/controllers` after the generator is run. Likewise for test, route, table, fixture and schema. These are all the files where they are named based off the model's plural name, but I think it would reduce confusion to put them in the corresponding folders even if it's just a single file in each.

change
```
/controllers
> controller.mustache
> test.mustache
> route.mustache
```

to this
```
/controllers
> /controllers/controller.mustache
> /tests/controllers/test.mustache
> /routes/route.mustache
```

**Comment by MadRabbit** [comment]
I think this one overlaps with #45 /cc @davidbanham

**Comment by davidbanham** [comment]
Yeah, it's probably more cognitive load than it's worth to not mirror the directory structure.

It does overlap a little. Makes sense to action this once #45 is complete.

**Comment by MadRabbit** [comment]
i've resolved this in the `thinky` branch
