### ISSUE TITLE
restify vs. express

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#62]
I keep forgetting to write this ticket. I'm wondering what drove you guys to switch from `express` to `restify`? It seems like it is modeled after express 2.0. It does pretty much all the same as express minus a huge number of features.

I find their argument about express being focused on views is a bit dated. You could kind stretch it this way with express 2.x, but express 4 is as much decoupled from views as it gets. html rendering is just a piece of middleware there, like everything else, you don't have to install it if you don't want to. the world moved on with express, and restify kind of stuck in 2012.

For example, it pushes you to write routes like this:
```js
module.exports = function(app) {
  app.use("/smth/smth", (req, res) => {
  });
};
```
There are plenty of articles online that suggest to do it this way, but that is because the way we did it back in the express 2.0 times. it was considered an anti-pattern for a long time now. basically because it breaks the abstraction level and creates coupling between an app and the routing. expressjs introduced a `Router` long time ago to solve this exact problem.

Here is an example how it is done in a modern express app. routes a recomposed of other routes and provide a single middleware that then mounted into an app.

https://github.com/Prismatik/opensourcify/blob/master/src/routes/index.js

Either way, I strongly suggest you reconsider the switch. In my opinion you won't win anything by marginalizing yourself from the mainstream. You just lock yourself out from new features and endless options of community built middleware

**Comment by MadRabbit** [comment]
Just to be clear, I'm discouraging you from trying different things, that is not my intention. But, I think you need to reconsider this when it comes to defining the _default_ way Prismatik will write apps

**Comment by davidbanham** [comment]
Historically I preferred Restify over Express for APIs because:

1) It had no view layer or templating mechanism, ensuring that it was really obvious this was a pure JSON API
2) It came with DTrace bindings built in out of the box
3) It was simple and lightweight

In the time since I formed that opinion:

1) Express no longer comes with a templating layer, you can just add one in
2) DTrace is an awesome tool, but is such a PITA to use that I've never actually done so For Reals. It's easier to just live with taking stack dumps and diffing them in the Chrome developer tools (ugh)
3) Express is super simple and lightweight these days

So yes, the time of Restify being better than Express is, for us, over. The big question now is should we standardise on Express, or on Koa or Hapi or something else?

**Comment by MadRabbit** [comment]
yeah, people used to bring the DTrace argument up a lot, but I'm yet to meet a real live developer who actually used the darn thing.

also, i think it is worth to add into the mixture the question of what the client wants? if I was your client and you've built a thing for me and now i want to say move the project in-house. Having it built in something relatively obscure will be a major pain point for me. I'm not even speaking about a possibility that the client will decide to sell their project. A non-mainstream base will drastically reduce the price. I reckon that won't exactly make them recommend our services to a friend

**Comment by nwinch** [comment]
I wouldn't mind trying one of those options.  I like the sound of the `Rout`ing features outlined for express 4.  That's cool.  TBH I don't know much about Koa or Hapi - other than by name - but wouldn't mind giving them a whirl if they fit the bill.

Regarding `restify` I especially like it for Dave's point 3).  From memory - to give some historical context particularly Nikolay's benefit - I don't recall that we performed a switch from one or the other (`express` or `restify`), but rather for some initial projects we chose an appropriate tool for the task that matched the criteria we needed to meet - and that happened to be `restify` at the time.  It then seemed to become part of the usual lineup - without any noteworthy problems that I can remember - and now with fresh eyes like Nikolay's, we have the opportunity to reassess.  I like `restify` but am also keen to use something else.

I remember reading stats somewhere that over 70% of relevant node/API thingy projects use express?

**Comment by davidbanham** [comment]
> also, i think it is worth to add into the mixture the question of what the client wants?

Definitely worth considering.

> I remember reading stats somewhere that over 70% of relevant node/API thingy projects use express?

I was about to type a thing about Express governance being a total shitshow, but when I was looking for an illustrative link it seems that they've figured it out. IBM has given up Express and handed it to the Node Foundation, which Doug Wilson is happy with so I guess he'll keep contributing. Yay!

In light of that, I think we should probably cut over to Express, with a view to moving to Koa once it becomes more mainstream alongside async/await.

**Comment by davidbanham** [comment]
Closing this since it seems like this is a decision everyone can get behind. Re-open if anyone disagrees.
