### ISSUE TITLE
JSCS vs. ESLint

### ISSUE THREAD

**Issue by MadRabbit** [Prismatik/redbeard#65]
Moving this from `redbeard-admin` here

I feel like JSCS was a good alternative to JSHint a year or two ago. But those days I think most projects standardized on a babel + eslint stack.

they kind of both do the same thing, but you're trying to standardize the stack so I think it would be only fitting to use it in here as well. even for the sheer least surprise factor.

*UPDATE* jscs 3 is actually utterly broken https://github.com/jscs-dev/node-jscs/issues/2219 they've already released several patch versions and the problem is still there. i had to fall back to 2.x for redbeard-admin in order to make this work. i think this adds to the story

**Comment by nwinch** [comment]
Now we can use this - https://github.com/Prismatik/eslint-config-prismatik

I'll mark this as "todo" as it's no longer a discussion.

**Comment by s-taylor** [comment]
We've implemented ES lint, so lets close this off.

**Comment by MadRabbit** [comment]
Wasn't this about having an eslint setup inside of the generated project though?

**Comment by s-taylor** [comment]
It wasn't clear from the description really. The current setup lints both the redbeard generator code, as well as a generated project (so the .mustache is linted). Copying the config over to the generated project is not yet done. I think it's somewhat different, so I'll open a new Issue #104.
