### ISSUE TITLE
Add supported npm version to package.json

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard#75]
Add npm v2 to `engines` property of `package.json` if we're not levelling up to 3 anytime soon.

**Comment by s-taylor** [comment]
My vote is we just ditch the root symlink and upgrade to npm3. I love the symlink but if we can't make it work I suggest we just get rid of it. We're not using `root` universally in our requires now anyway.

**Comment by davidbanham** [comment]
There's a post install hook hack to make the symlink work with 3. We have to be able to run on Node 6. Can't pin to 4 forever.
